/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Alumno;
import Clases.Curso;
import Clases.Nivel;
import Clases.PorcentajedeSexo;
import GestorBD.GestorBD;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Emiliano
 */
public class Reporte extends javax.swing.JFrame {

    /**
     * Creates new form Reporte
     */
    public Reporte() {
        initComponents();
        CargarLista();
        CargarComboNiveles();
    }

    public void CargarComboNiveles() {
        GestorBD gestor = new GestorBD();

        ArrayList<Nivel> lista = gestor.ObtenerNiveles();

        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (Nivel t : lista) {
            model.addElement(t);
        }
        cboNivel.setModel(model);
    }

    private void CargarLista() {
        GestorBD gestor = new GestorBD();
        ArrayList<Curso> venta = gestor.ObtenerCursos();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Id", "Nombre", "Cupo restante", "Turno"});
        for (Curso v : venta) {
            modelo.addRow(new Object[]{v.getIdcurso(), v.getNombre_curso(), v.getCapacidad(), v.getTurno().getTurno()});
        }
        tblCursos.setModel(modelo);
//        //esto es necesario para ocultar el campo id y no mostrarlo en la tabla
//        TableColumn columna = tblCursos.getColumnModel().getColumn(0);
//        //coloco un tamaño maximo y minimo de 0 
//        columna.setMaxWidth(0);
//        columna.setMinWidth(0);
//        columna.setPreferredWidth(0);
//        //desactivo la propiedad para poder aumentar el tamaño de la celda con el mouse
//        TableColumn columna1 = tblCursos.getColumnModel().getColumn(0);
//        columna1.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCursos = new javax.swing.JTable();
        btnPorcentaje = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReporte = new javax.swing.JTable();
        btnAlumnosxCurso = new javax.swing.JButton();
        cboNivel = new javax.swing.JComboBox<>();
        btnNivel = new javax.swing.JButton();
        btnTarde = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCursos);

        btnPorcentaje.setText("Calcular Porcentaje de genero");
        btnPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorcentajeActionPerformed(evt);
            }
        });

        tblReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblReporte);

        btnAlumnosxCurso.setText("Ver Alumnos del Curso");
        btnAlumnosxCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosxCursoActionPerformed(evt);
            }
        });

        btnNivel.setText("Alumnos por Nivel");
        btnNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivelActionPerformed(evt);
            }
        });

        btnTarde.setText("Alumnos que Asisten a la Tarde");
        btnTarde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTardeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPorcentaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlumnosxCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTarde, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPorcentaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlumnosxCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTarde))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorcentajeActionPerformed

        try {
            int curso = Integer.parseInt((tblCursos.getValueAt(tblCursos.getSelectedRow(), 0).toString()));
            GestorBD gestor = new GestorBD();
            ArrayList<PorcentajedeSexo> venta = gestor.Obtenergeneros(curso);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new String[]{"Femenino", "Masculino", "otro"});
            for (PorcentajedeSexo v : venta) {
                modelo.addRow(new Object[]{v.getCantiFemenenino(), v.getCantiMasculino(), v.getCantidadSinSexo()});
            }
            tblReporte.setModel(modelo);
            PorcentajedeSexo p = new PorcentajedeSexo();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "seleccione un curso");
        }


    }//GEN-LAST:event_btnPorcentajeActionPerformed

    private void btnAlumnosxCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosxCursoActionPerformed
        try {
            int curso = Integer.parseInt((tblCursos.getValueAt(tblCursos.getSelectedRow(), 0).toString()));
            GestorBD gestor = new GestorBD();
            ArrayList<Alumno> venta = gestor.ObtenerAlumnosporCurso(curso);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new String[]{"Legajo", "Nombre", "Nivel", "Curso", "Sexo", "idcurso"});
            for (Alumno v : venta) {
                modelo.addRow(new Object[]{v.getLegajo(), v.getApellido(), v.getNivel().getNombreNivel(), v.getCurso().getNombre_curso(), v.getSexo().getSexo(), v.getCurso().getIdcurso()});
            }
            tblReporte.setModel(modelo);
            //esto es necesario para ocultar el campo id y no mostrarlo en la tabla
            TableColumn columna = tblReporte.getColumnModel().getColumn(5);
            //coloco un tamaño maximo y minimo de 0 
            columna.setMaxWidth(0);
            columna.setMinWidth(0);
            columna.setPreferredWidth(0);
            //desactivo la propiedad para poder aumentar el tamaño de la celda con el mouse
            TableColumn columna1 = tblReporte.getColumnModel().getColumn(5);
            columna1.setResizable(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "seleccione un curso");
        }
    }//GEN-LAST:event_btnAlumnosxCursoActionPerformed

    private void btnNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivelActionPerformed

        String curso = (String) cboNivel.getSelectedItem().toString();
        
        
        System.out.println(curso);
        
        GestorBD gestor = new GestorBD();
        ArrayList<Alumno> venta = gestor.ObtenerAlumnosPorNivel(curso);
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Legajo", "Nombre", "Nivel", "Curso", "Sexo", "idcurso"});
        for (Alumno v : venta) {
            modelo.addRow(new Object[]{v.getLegajo(), v.getApellido(), v.getNivel().getNombreNivel(), v.getCurso().getNombre_curso(), v.getSexo().getSexo(), v.getCurso().getIdcurso()});
        }
        tblReporte.setModel(modelo);
        //esto es necesario para ocultar el campo id y no mostrarlo en la tabla
        TableColumn columna = tblReporte.getColumnModel().getColumn(5);
        //coloco un tamaño maximo y minimo de 0 
        columna.setMaxWidth(0);
        columna.setMinWidth(0);
        columna.setPreferredWidth(0);
        //desactivo la propiedad para poder aumentar el tamaño de la celda con el mouse
        TableColumn columna1 = tblReporte.getColumnModel().getColumn(5);
        columna1.setResizable(false);
    }//GEN-LAST:event_btnNivelActionPerformed

    private void btnTardeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTardeActionPerformed

        GestorBD gestor = new GestorBD();
        ArrayList<Alumno> venta = gestor.ObtenerAlumnosTarde();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Legajo", "Nombre", "Nivel", "Curso", "Sexo", "idcurso"});
        for (Alumno v : venta) {
            modelo.addRow(new Object[]{v.getLegajo(), v.getApellido(), v.getNivel().getNombreNivel(), v.getCurso().getNombre_curso(), v.getSexo().getSexo(), v.getCurso().getIdcurso()});
        }
        tblReporte.setModel(modelo);
        //esto es necesario para ocultar el campo id y no mostrarlo en la tabla
        TableColumn columna = tblReporte.getColumnModel().getColumn(5);
        //coloco un tamaño maximo y minimo de 0 
        columna.setMaxWidth(0);
        columna.setMinWidth(0);
        columna.setPreferredWidth(0);
        //desactivo la propiedad para poder aumentar el tamaño de la celda con el mouse
        TableColumn columna1 = tblReporte.getColumnModel().getColumn(5);
        columna1.setResizable(false);
    }//GEN-LAST:event_btnTardeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumnosxCurso;
    private javax.swing.JButton btnNivel;
    private javax.swing.JButton btnPorcentaje;
    private javax.swing.JButton btnTarde;
    private javax.swing.JComboBox<String> cboNivel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCursos;
    private javax.swing.JTable tblReporte;
    // End of variables declaration//GEN-END:variables
}
